name: 'Deploy Teams tab'
author: 'pl4nty'
description: 'Deploy a custom tab to Microsoft Teams'
branding:
    icon: 'upload-cloud'
    color: 'purple'
inputs:
  TENANT_ID:
    description: 'AzureAD tenant (directory) ID'
    required: true
  APP_ID:
    description: 'AzureAD application ID'
    required: true
  APP_SECRET:
    description: 'AzureAD application secret'
    required: true
outputs:
  time:
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'dist/index.js'